name: Test Runner

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-runner:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Install test requirements
        run: pip install -r test-requirements.txt
      - name: Run tests
        # Run tox using the version of Python in `PATH`
        run: coverage run -m pytest
      - name: Generate coverage report
        run: coverage xml
      - name: Upload coverage report
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python == '3.11' }}
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/coverage.xml:coverage.py